#!/usr/bin/env bash
#
# Render documentation and open a browser window with the rendered docs.

set -o errexit
set -o pipefail
set -o nounset

# shellcheck disable=SC1091
source utils.sh

fancy_echo "Render Quarto (general) documentation"
poetry run quarto preview docs
