#!/usr/bin/env bash
#
# Render documentation and open a browser window with the rendered docs.

set -o errexit
set -o pipefail
set -o nounset

# shellcheck disable=SC1091
source utils.sh

fancy_echo "Render pdoc (API) documentation"
poetry run python -m pdoc --docformat google redpsy/
